Update patch set 1
Patch Set 1:

Here:
11-20 20:50:57.684  6097  6097 E Parcel  : Class not found when unmarshalling: com.android.mail.providers.Conversation
11-20 20:50:57.684  6097  6097 E Parcel  : java.lang.ClassNotFoundException: com.android.mail.providers.Conversation
11-20 20:50:57.684  6097  6097 E Parcel  : 	at java.lang.Class.classForName(Native Method)
11-20 20:50:57.684  6097  6097 E Parcel  : 	at java.lang.Class.forName(Class.java:324)
11-20 20:50:57.684  6097  6097 E Parcel  : 	at android.os.Parcel.readParcelableCreator(Parcel.java:2404)
11-20 20:50:57.684  6097  6097 E Parcel  : 	at android.os.Parcel.readParcelable(Parcel.java:2358)
11-20 20:50:57.684  6097  6097 E Parcel  : 	at android.os.Parcel.readValue(Parcel.java:2264)
11-20 20:50:57.684  6097  6097 E Parcel  : 	at android.os.Parcel.readArrayMapInternal(Parcel.java:2614)
11-20 20:50:57.684  6097  6097 E Parcel  : 	at android.os.BaseBundle.unparcel(BaseBundle.java:221)
11-20 20:50:57.684  6097  6097 E Parcel  : 	at android.os.Bundle.getParcelable(Bundle.java:786)
11-20 20:50:57.684  6097  6097 E Parcel  : 	at android.content.Intent.getParcelableExtra(Intent.java:5581)
11-20 20:50:57.684  6097  6097 E Parcel  : 	at android.app.Activity.getReferrer(Activity.java:4699)
11-20 20:50:57.684  6097  6097 E Parcel  : 	at com.android.internal.app.ResolverActivity.getReferrerPackageName(ResolverActivity.java:407)
11-20 20:50:57.684  6097  6097 E Parcel  : 	at com.android.internal.app.ResolverActivity.onCreate(ResolverActivity.java:237)
11-20 20:50:57.684  6097  6097 E Parcel  : 	at com.android.internal.app.ResolverActivity.onCreate(ResolverActivity.java:190)
11-20 20:50:57.684  6097  6097 E Parcel  : 	at android.app.Activity.performCreate(Activity.java:6251)
11-20 20:50:57.684  6097  6097 E Parcel  : 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
11-20 20:50:57.684  6097  6097 E Parcel  : 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
11-20 20:50:57.684  6097  6097 E Parcel  : 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
11-20 20:50:57.684  6097  6097 E Parcel  : 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
11-20 20:50:57.684  6097  6097 E Parcel  : 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
11-20 20:50:57.684  6097  6097 E Parcel  : 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-20 20:50:57.684  6097  6097 E Parcel  : 	at android.os.Looper.loop(Looper.java:148)
11-20 20:50:57.684  6097  6097 E Parcel  : 	at android.app.ActivityThread.main(ActivityThread.java:5461)
11-20 20:50:57.684  6097  6097 E Parcel  : 	at java.lang.reflect.Method.invoke(Native Method)
11-20 20:50:57.684  6097  6097 E Parcel  : 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-20 20:50:57.684  6097  6097 E Parcel  : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-20 20:50:57.684  6097  6097 E Parcel  : Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.mail.providers.Conversation" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]
11-20 20:50:57.684  6097  6097 E Parcel  : 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
11-20 20:50:57.684  6097  6097 E Parcel  : 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
11-20 20:50:57.684  6097  6097 E Parcel  : 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
11-20 20:50:57.684  6097  6097 E Parcel  : 	... 25 more
11-20 20:50:57.684  6097  6097 E Parcel  : 	Suppressed: java.lang.ClassNotFoundException: com.android.mail.providers.Conversation
11-20 20:50:57.684  6097  6097 E Parcel  : 		at java.lang.Class.classForName(Native Method)
11-20 20:50:57.684  6097  6097 E Parcel  : 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
11-20 20:50:57.684  6097  6097 E Parcel  : 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
11-20 20:50:57.684  6097  6097 E Parcel  : 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
11-20 20:50:57.684  6097  6097 E Parcel  : 		... 26 more
11-20 20:50:57.684  6097  6097 E Parcel  : 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

Patch-set: 1